### ISSUE TITLE
Output is always in JSON

### ISSUE THREAD

**Issue by NeckBeardPrince** [logstash-plugins/logstash-output-file#19]
Input file is in plain

Output file is always in JSON even if setting codec to plain.

Latest version.

**Comment by purbon** [comment]
There is no codec support for this plugin, I understand what you would like to use your codec of choice, right?

**Comment by wiibaa** [comment]
@purbon codec support is pending review ;) => https://github.com/logstash-plugins/logstash-output-file/pull/9

**Comment by purbon** [comment]
@wiibaa will take a look there soon :+1: thanks for pointing it out.

**Comment by purbon** [comment]
Fixed with #9
