### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by Jacox98** [logstash-plugins/logstash-output-file#71]
Hi my config is this

input
{
    beats
    {
        ssl => false
        host => "0.0.0.0"
        port => 5044
    }
    gelf
    {
        host => "0.0.0.0"
        port => 12201
    }
    http
    {
        ssl => false
        host => "0.0.0.0"
        port => 8888
    }
    tcp
    {
        mode => "server"
        host => "0.0.0.0"
        port => 5010
    }
    udp
    {
        host => "0.0.0.0"
        port => 5000
    }
}

filter {
  geoip {
    source => "[event_data][IpAddress]"
  }
}

output {
    elasticsearch
    {
        hosts => ["127.0.0.1:9200"]
        document_id => "%{logstash_checksum}"
        index => "logstash-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
    file
     {
      message_format => "%{[time] - %{[message]}"
      path => "/LOG/%{event_data.TargetDomainName}/LOG-%{+YYYY-MM-dd}.txt"
      file_mode => 0777
      codec => line {}
     }

}
But there aren't file output, can u help me?Thanks

**Comment by robbavey** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
